# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "895aa964757513c17494314400155e2d"
name = "pointswipe-app"
handle = "pointswipe-app"
application_url = "https://undergraduate-boutique-destination-operators.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pointswipe.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://undergraduate-boutique-destination-operators.trycloudflare.com/auth/callback",
  "https://undergraduate-boutique-destination-operators.trycloudflare.com/auth/shopify/callback",
  "https://undergraduate-boutique-destination-operators.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
